# Generated by Django 4.0.1 on 2022-04-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('is_active', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'Book',
            },
        ),
    ]
