# Generated by Django 4.0.1 on 2022-04-12 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_active',
        ),
    ]
