# Generated by Django 4.0.1 on 2022-04-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_App', '0002_remove_book_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
    ]
